package com.swivel.onboarding.ui.splash

/**
 * @author Yohan Dushmantha
 * @class SplashTasks
 *
 * progress task events
 */
enum class SplashTasks(val text : String) {
    CREATE_KEYSTORE_SUCCESS("CRAETE_KEYSTORE_SUCCESS"),
    CREATE_KEYSTORE_FAILURE("CREATE_KEYSTORE_FAILURE"),
    DEVICE_IS_ROOTED("DEVICE_IS_ROOTED"),
    DEVICE_IS_NOT_ROOTED("DEVICE_IS_NOT_ROOTED"),
    HAS_PHONE_STATE_PERMISSION("HAS_PHONE_STATE_PERMISSION"),
    NO_PHONE_STATE_PERMISSION("NO_PHONE_STATE_PERMISSION"),
    GRANT_PHONE_STATE_PERMISSION("GRANT_PHONE_STATE_PERMISSION"),
    DENY_PHONE_STATE_PERMISSION("DENY_PHONE_STATE_PERMISSION"),
    HAS_ACCESS_NETWORK_STATE_PERMISSION("HAS_ACCESS_NETWORK_STATE_PERMISSION"),
    NO_ACCESS_NETWORK_STATE_PERMISSION("HAS_ACCESS_NETWORK_STATE_PERMISSION"),
    GRANT_ACCESS_NETWORK_STATE_PERMISSION("HAS_ACCESS_NETWORK_STATE_PERMISSION"),
    DENY_ACCESS_NETWORK_STATE_PERMISSION("HAS_ACCESS_NETWORK_STATE_PERMISSION"),
    DEVICE_INFO_LOADED("DEVICE_INFO_LOADED"),
    DEVICE_INFO_NOT_LOADED("DEVICE_INFO_NOT_LOADED"),
    HAS_VALID_SESSION("HAS_VALID_SESSION"),
    AUTH_DATA_LOADED("AUTH_DATA_LOADED"),
    AUTH_DATA_NOT_LOADED("AUTH_DATA_NOT_LOADED"),
    NO_VALID_SESSION("NO_VALID_SESSION"),
    SYSTEM_CONFIGURATION_LOADED_SUCCESSFULLY("SYSTEM_CONFIGURATION_LOADED_SUCCESSFULLY"),
    SYSTEM_CONFIGURATION_LOADING_FAILED("SYSTEM_CONFIGURATION_LOADING_FAILED")
}